### ISSUE TITLE
An error is displayed when trying to save the Server Settings in the Admin Panel

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs-cloud#234] opened 2021-12-10 14:10 UTC
**[Affected Versions]:**
- Firefox Release 94.02
- Chrome 96
- Safari v15.1

**[Affected Platforms]:**
- Windows 10x64
- macOS BigSur v11.6.1

**[Prerequisites]:**
- Your Hubs Cloud stack is set up.
- The Admin Panel is opened.

**[Steps to reproduce]:**
1. Navigate to the Server Settings section.
2. Edit one of the field available.
3. Click the Save button and observe the behavior.

**[Expected results]:**
- The settings are saved.

**[Actual results]:**
- An Internal error is displayed and the settings are NOT applied.

**[Notes]:**
- Attached is a screen recording of the issue: 
![admin-internal-error-hc-oct-release](https://user-images.githubusercontent.com/40061643/145586684-e63a6749-ddd4-4b07-a0a4-b33ba03d2324.gif)

**Comment by brianpeiris** [comment] 2021-12-18 05:04
Here are some facts I've gathered about this issue:
- This error is happening because ita fails to flush habitat configs.
- Ita uses the hubs-configtool library to flush configs to habitat.
- The hubs-configtool flushes configs by executing the `bio config apply` command.
- That command is failing due to incorrect permissions on a public key file in `/hab/cache/keys/`.
- The public key file has incorrect permissions because it is deposited there when the janus-gateway package gets updated.
- We have infrastructure code that usually changes the permissions on these public key files, but that mechanism does not account for new public key files that are deposited as part of a package update.
- The janus-gateway package is unique because it was built recently with a private key file that is newer than the rest of the packages.
- Some older public key files exist in the `/hab/cache/keys/` directory, and they have their permissions corrected properly. This is because they were deposited there during the AMI provisioning stage. (This might not be a fact, since I'm uncertain about when the AMI provisioning step occurs.)

Based on that information, here are some possible solutions to choose from:
- We re-build the janus-gateway package with a working key file.
- We re-build the AMI to include the new public key.
- We figure out a mechanism to update the permissions on new public key files when they are deposited by a package update.

**Comment by brianpeiris** [comment] 2022-01-04 12:46
We have deployed a fix for this issue to the beta stacks. Existing beta stacks will not be fixed automatically. You will have to either terminate all your EC2 instances, or destroy and re-create the stacks for the fix to take effect.

**Comment by SV-AndreiC** [comment] 2022-01-05 14:51
I have verified this issue and it's no longer reproducible. Now when editing the server settings fields and saving the changes we get a "Settings saved" pop-up message.

**Comment by brianpeiris** [comment] 2022-01-11 16:47
I think we can mark this as closed. The fix involved re-deploying the janus-gateway (dialog) package with a proper key file, so there wasn't a code change involved.
Feel free to reopen if needed.

**Closed by brianpeiris** 2022-01-11 16:47 UTC
Labels: [QA]:Blocker-issue, [QA]:Regression, HC-October-Release
