### ISSUE TITLE
Enterprise multi-server setup: object in one app server's database is missing in the other returning 401

### ISSUE THREAD

**Issue by robinkwilson** [mozilla/hubs-cloud#89] opened 2020-07-23 18:22 UTC
From a user via hubs@.

Environment
- HC Enterprise 2 app x 2 streaming

Issues: 
401 errors returned for some objects. In one room, it will be spawned, in another, it will return 401. Likely because the room is handled by the app server with the object in db, then handled by the one without. 
We are consistently getting 401 errors when we deploy more than one instance. After further digging, we realize some of the objects we create on one app instance does not get replicated into the other instances’ PostgreSQL database. We have enabled sticky session on the load balancer and opened security group to all/all to all IP addresses inside the VPC, but that did not fix the issue. 

Expected:
All objects added to the cluster, should be found.

**Comment by misslivirose** [comment] 2020-11-19 23:46
This is a significant issue for any significant deployment that scales or wants to have a redundancy plan in place for the deployment; essentially, there is a likelihood (we need to figure out root cause and how frequently this happens) that media will fail to load for some % of the users depending on the app server they are connected to.

**Comment by gfodor** [comment] 2020-11-20 00:57
This may be the rate limiting being triggered but hard to say - the rate
limiting is node local and I’m not sure offhand if the the media loading
can be in the rate limited control flow - the proposed theory in the
original submission is not right because there is a single shared database
between all nodes.

**Comment by brianpeiris** [comment] 2020-12-14 18:32
This might be a duplicate of #116, though it's odd that the description mentions 401 errors, specifically. #116 presents with 500/504 errors.

**Closed** 2020-12-14 18:32 UTC
Labels: P1, needs repro, reliability
